[package]
name = "prompt-box"
version = "0.1.0"
description = "A Image Prompt Manage Tauri App"
authors = ["CIPFZ"]
edition = "2021"

[lib]
name = "prompt_box_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["devtools"] }
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
# 我们的核心业务库
rusqlite = { version = "0.32", features = ["bundled"] }
uuid = { version = "1", features = ["v4"] }
chrono = { version = "0.4", features = ["serde"] }
tauri-plugin-clipboard-manager = "2"
